//JUST DEFINING SOME NAMES OF ACTIONS

export const CREATE_GROUP_ERROR = 'CREATE_GROUP_ERROR';
export const CREATE_GROUP_SUCCESS = 'CREATE_GROUP_SUCCESS';

export const REMOVE_GROUP_ERROR = 'REMOVE_GROUP_ERROR';
export const REMOVE_GROUP_SUCCESS = 'REMOVE_GROUP_SUCCESS';

export const LOAD_GROUPS_SUCCESS = 'LOAD_GROUPS_SUCCESS';
export const UNLOAD_GROUPS_SUCCESS = 'UNLOAD_GROUPS_SUCCESS';

export const UPDATE_GROUP_ERROR = 'UPDATE_GROUP_ERROR';
export const UPDATE_GROUP_SUCCESS = 'UPDATE_GROUP_SUCCESS';